name: Router_OS.rsc
on:
  schedule:
    - cron: "0 17 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    name: Build DNS Static
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download DNS Static
        run: chmod +x ./Config/DNS_Static/DNS_Static.sh&&./Config/DNS_Static/DNS_Static.sh
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}