name: Router_OS.rsc
on:
  schedule:
    - cron: "* 18 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    name: Build DNS Static.rsc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build ISP IP Address
        run:  |
          chmod +x ./Config/DNS Static/DNS Static.sh
          ./Config/DNS Static/DNS Static.sh
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
