name: Build Adblock.rsc
on:
  schedule:
    - cron: "* 18 * * *"
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    name: runs-on ubuntu-latest
    runs-on: ubuntu-latest